### ISSUE TITLE
Early project planning and TODO

### ISSUE THREAD

**Issue by Hexx13** [Hexx13/LabTest3Prep-Web-Frameworks#1]
### TODO's
- [ ] Add valid redirect after successful login
- [ ] Add roles apart from User & Admin
   - Student?
   - Contractor/Luthier/Employee?
   - Teacher?
- [ ] only allow Admin to access User CRUD

### Ideas for pages
- Store catalog page/Online Store
- Lesson booking
- Contractors for instrument set-up/repair/custom builds
- Contact/Location 
- Account
